# Generated by Django 3.1.1 on 2020-11-02 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockattribute', models.CharField(max_length=20)),
                ('stockname', models.CharField(max_length=100)),
                ('stockprice', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tradereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=10)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=50)),
                ('stock', models.CharField(choices=[('ASHOKLEY', 'ASHOKLEY'), ('WIPRO', 'WIPRO'), ('RAJESHEXPO', 'RAJESHEXPO'), ('AMBUJACEM', 'AMBUJACEM'), ('MM', 'MM'), ('ONGC', 'ONGC'), ('DMART', 'DMART'), ('SUNPHARMA', 'SUNPHARMA'), ('stock9', 'stock9'), ('ADANIPOWER', 'ADANIPOWER')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_trade_inter', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_trade_inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('ASHOKLEY', 'ASHOKLEY'), ('WIPRO', 'WIPRO'), ('RAJESHEXPO', 'RAJESHEXPO'), ('AMBUJACEM', 'AMBUJACEM'), ('MM', 'MM'), ('ONGC', 'ONGC'), ('DMART', 'DMART'), ('SUNPHARMA', 'SUNPHARMA'), ('stock9', 'stock9'), ('ADANIPOWER', 'ADANIPOWER')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_of_stock_international', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_of_stock_international', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASHOKLEY', models.IntegerField(default=0)),
                ('WIPRO', models.IntegerField(default=0)),
                ('RAJESHEXPO', models.IntegerField(default=0)),
                ('AMBUJACEM', models.IntegerField(default=0)),
                ('MM', models.IntegerField(default=0)),
                ('ONGC', models.IntegerField(default=0)),
                ('DMART', models.IntegerField(default=0)),
                ('SUNPHARMA', models.IntegerField(default=0)),
                ('stock9', models.IntegerField(default=0)),
                ('ADANIPOWER', models.IntegerField(default=0)),
                ('userbalance', models.FloatField(default=1000000.0)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting', models.CharField(max_length=100)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
