# Generated by Django 3.1.1 on 2020-11-02 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockattribute', models.CharField(max_length=20)),
                ('stockname', models.CharField(max_length=100)),
                ('stockprice', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tradereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=10)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=50)),
                ('stock', models.CharField(choices=[('TM', 'TM'), ('UL', 'UL'), ('CVX', 'CVX'), ('BRK', 'BRK'), ('JPM', 'JPM'), ('T', 'T'), ('WFC', 'WFC'), ('HD', 'HD'), ('KO', 'KO'), ('VISA', 'VISA'), ('WMT', 'WMT'), ('AXP', 'AXP'), ('BA', 'BA'), ('PFE', 'PFE'), ('VZ', 'VZ')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_trade_inter', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_trade_inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('TM', 'TM'), ('UL', 'UL'), ('CVX', 'CVX'), ('BRK', 'BRK'), ('JPM', 'JPM'), ('T', 'T'), ('WFC', 'WFC'), ('HD', 'HD'), ('KO', 'KO'), ('VISA', 'VISA'), ('WMT', 'WMT'), ('AXP', 'AXP'), ('BA', 'BA'), ('PFE', 'PFE'), ('VZ', 'VZ')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_of_stock_international', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_of_stock_international', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TM', models.IntegerField(default=0)),
                ('UL', models.IntegerField(default=0)),
                ('CVX', models.IntegerField(default=0)),
                ('BRK', models.IntegerField(default=0)),
                ('JPM', models.IntegerField(default=0)),
                ('T', models.IntegerField(default=0)),
                ('WFC', models.IntegerField(default=0)),
                ('HD', models.IntegerField(default=0)),
                ('KO', models.IntegerField(default=0)),
                ('VISA', models.IntegerField(default=0)),
                ('userbalance', models.FloatField(default=1000000.0)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting', models.CharField(max_length=100)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_inter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
