# Generated by Django 3.1.1 on 2020-11-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='AAPL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='ADBE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='AXP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='BA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='BABA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='FB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='GAZP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='GS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='HMC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='INTC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='MCD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='MSFT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='NFLX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='PFE',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='PYPL',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='QCOM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='TCEHY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='TSLA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='TXN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='VWS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='VZ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='WMT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='ZM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.CharField(choices=[('TM', 'TM'), ('UL', 'UL'), ('CVX', 'CVX'), ('BRK', 'BRK'), ('JPM', 'JPM'), ('T', 'T'), ('WFC', 'WFC'), ('HD', 'HD'), ('KO', 'KO'), ('VISA', 'VISA'), ('WMT', 'WMT'), ('AXP', 'AXP'), ('BA', 'BA'), ('PFE', 'PFE'), ('VZ', 'VZ'), ('HMC', 'HMC'), ('QCOM', 'QCOM'), ('NFLX', 'NFLX'), ('FB', 'FB'), ('ADBE', 'ADBE'), ('VWS', 'VWS'), ('GAZP', 'GAZP'), ('GS', 'GS'), ('MCD', 'MCD'), ('ZM', 'ZM'), ('PYPL', 'PYPL'), ('TCECHY', 'TCECHY'), ('BABA', 'BABA'), ('AAPL', 'AAPL'), ('MSFT', 'MSFT'), ('TSLA', 'TSLA'), ('TXN', 'TXN'), ('INTC', 'INTC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tradereq',
            name='stock',
            field=models.CharField(choices=[('TM', 'TM'), ('UL', 'UL'), ('CVX', 'CVX'), ('BRK', 'BRK'), ('JPM', 'JPM'), ('T', 'T'), ('WFC', 'WFC'), ('HD', 'HD'), ('KO', 'KO'), ('VISA', 'VISA'), ('WMT', 'WMT'), ('AXP', 'AXP'), ('BA', 'BA'), ('PFE', 'PFE'), ('VZ', 'VZ'), ('HMC', 'HMC'), ('QCOM', 'QCOM'), ('NFLX', 'NFLX'), ('FB', 'FB'), ('ADBE', 'ADBE'), ('VWS', 'VWS'), ('GAZP', 'GAZP'), ('GS', 'GS'), ('MCD', 'MCD'), ('ZM', 'ZM'), ('PYPL', 'PYPL'), ('TCECHY', 'TCECHY'), ('BABA', 'BABA'), ('AAPL', 'AAPL'), ('MSFT', 'MSFT'), ('TSLA', 'TSLA'), ('TXN', 'TXN'), ('INTC', 'INTC')], max_length=100),
        ),
    ]
