# Generated by Django 3.1.1 on 2020-11-01 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stock_intt',
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='stockprice',
            field=models.FloatField(default=0),
        ),
    ]
