# Generated by Django 3.1.1 on 2020-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('international', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.CharField(choices=[('ASHOKLEY', 'ASHOKLEY'), ('WIPRO', 'WIPRO'), ('RAJESHEXPO', 'RAJESHEXPO'), ('AMBUJACEM', 'AMBUJACEM'), ('MM', 'MM'), ('ONGC', 'ONGC'), ('DMART', 'DMART'), ('SUNPHARMA', 'SUNPHARMA'), ('stock9', 'stock9'), ('ADANIPOWER', 'ADANIPOWER'), ('stock11', 'stock11'), ('stock12', 'stock12'), ('stock13', 'stock13'), ('stock14', 'stock14'), ('stock15', 'stock15')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tradereq',
            name='stock',
            field=models.CharField(choices=[('ASHOKLEY', 'ASHOKLEY'), ('WIPRO', 'WIPRO'), ('RAJESHEXPO', 'RAJESHEXPO'), ('AMBUJACEM', 'AMBUJACEM'), ('MM', 'MM'), ('ONGC', 'ONGC'), ('DMART', 'DMART'), ('SUNPHARMA', 'SUNPHARMA'), ('stock9', 'stock9'), ('ADANIPOWER', 'ADANIPOWER'), ('stock11', 'stock11'), ('stock12', 'stock12'), ('stock13', 'stock13'), ('stock14', 'stock14'), ('stock15', 'stock15')], max_length=100),
        ),
    ]
