# Generated by Django 3.1.1 on 2020-11-02 00:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('international', '0002_auto_20201102_0425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_intt',
            new_name='Stock',
        ),
    ]
