# Generated by Django 3.1.1 on 2020-10-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockName', models.CharField(blank=True, max_length=100)),
                ('CurrentPrice', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
