# Generated by Django 3.1.1 on 2020-11-02 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockattribute', models.CharField(default='STOCK', max_length=20)),
                ('stockname', models.CharField(max_length=100)),
                ('stockprice', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tradereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=10)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='pending', max_length=50)),
                ('stock', models.CharField(choices=[('ASHOKLEY', 'ASHOKLEY'), ('WIPRO', 'WIPRO'), ('RAJESHEXPO', 'RAJESHEXPO'), ('AMBUJACEM', 'AMBUJACEM'), ('MM', 'MM'), ('ONGC', 'ONGC'), ('DMART', 'DMART'), ('SUNPHARMA', 'SUNPHARMA'), ('HINDUUNILVR', 'HINDUUNILVR'), ('ADANIPOWER', 'ADANIPOWER'), ('TATASTEEL', 'TATASTEEL'), ('IOC', 'IOC'), ('JINDALSTL', 'JINDALSTL'), ('INDIAMART', 'INDIAMART'), ('RELIANCE', 'RELIANCE'), ('INFOSYS', 'INFOSYS'), ('BATA', 'BATA'), ('BHARTIARTL', 'BHARTIARTL'), ('MARUTI', 'MARUTI'), ('ITC', 'ITC'), ('HDFCBANK', 'HDFCBANK'), ('IGL', 'IGL'), ('VOLTAS', 'VOLTAS'), ('BAJFINANCE', 'BAJFINANCE'), ('SBI', 'SBI'), ('CIPLA', 'CIPLA'), ('TCS', 'TCS'), ('LT', 'LT'), ('ASIANPAINT', 'ASIANPAINT'), ('ICICIPRULI', 'ICICIPRULI'), ('PVR', 'PVR'), ('PIDILITIND', 'PIDILITIND'), ('TRENT', 'TRENT')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_trade', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_trade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('ASHOKLEY', 'ASHOKLEY'), ('WIPRO', 'WIPRO'), ('RAJESHEXPO', 'RAJESHEXPO'), ('AMBUJACEM', 'AMBUJACEM'), ('MM', 'MM'), ('ONGC', 'ONGC'), ('DMART', 'DMART'), ('SUNPHARMA', 'SUNPHARMA'), ('HINDUUNILVR', 'HINDUUNILVR'), ('ADANIPOWER', 'ADANIPOWER'), ('TATASTEEL', 'TATASTEEL'), ('IOC', 'IOC'), ('JINDALSTL', 'JINDALSTL'), ('INDIAMART', 'INDIAMART'), ('RELIANCE', 'RELIANCE'), ('INFOSYS', 'INFOSYS'), ('BATA', 'BATA'), ('BHARTIARTL', 'BHARTIARTL'), ('MARUTI', 'MARUTI'), ('ITC', 'ITC'), ('HDFCBANK', 'HDFCBANK'), ('IGL', 'IGL'), ('VOLTAS', 'VOLTAS'), ('BAJFINANCE', 'BAJFINANCE'), ('SBI', 'SBI'), ('CIPLA', 'CIPLA'), ('TCS', 'TCS'), ('LT', 'LT'), ('ASIANPAINT', 'ASIANPAINT'), ('ICICIPRULI', 'ICICIPRULI'), ('PVR', 'PVR'), ('PIDILITIND', 'PIDILITIND'), ('TRENT', 'TRENT')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_of_stock', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASHOKLEY', models.IntegerField(default=0)),
                ('WIPRO', models.IntegerField(default=0)),
                ('RAJESHEXPO', models.IntegerField(default=0)),
                ('AMBUJACEM', models.IntegerField(default=0)),
                ('MM', models.IntegerField(default=0)),
                ('ONGC', models.IntegerField(default=0)),
                ('DMART', models.IntegerField(default=0)),
                ('SUNPHARMA', models.IntegerField(default=0)),
                ('HINDUUNILVR', models.IntegerField(default=0)),
                ('ADANIPOWER', models.IntegerField(default=0)),
                ('TATASTEEL', models.IntegerField(default=0)),
                ('IOC', models.IntegerField(default=0)),
                ('JINDALSTL', models.IntegerField(default=0)),
                ('INDIAMART', models.IntegerField(default=0)),
                ('RELIANCE', models.IntegerField(default=0)),
                ('INFOSYS', models.IntegerField(default=0)),
                ('BATA', models.IntegerField(default=0)),
                ('BHARTIARTL', models.IntegerField(default=0)),
                ('MARUTI', models.IntegerField(default=0)),
                ('ITC', models.IntegerField(default=0)),
                ('HDFCBANK', models.IntegerField(default=0)),
                ('IGL', models.IntegerField(default=0)),
                ('VOLTAS', models.IntegerField(default=0)),
                ('BAJFINANCE', models.IntegerField(default=0)),
                ('SBI', models.IntegerField(default=0)),
                ('CIPLA', models.IntegerField(default=0)),
                ('TCS', models.IntegerField(default=0)),
                ('LT', models.IntegerField(default=0)),
                ('ASIANPAINT', models.IntegerField(default=0)),
                ('ICICIPRULI', models.IntegerField(default=0)),
                ('PVR', models.IntegerField(default=0)),
                ('PIDILITIND', models.IntegerField(default=0)),
                ('TRENT', models.IntegerField(default=0)),
                ('userbalance', models.FloatField(default=1000000.0)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting', models.CharField(max_length=100)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
