# Generated by Django 3.1.1 on 2020-10-04 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='CurrentPrice',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='StockName',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('stock1', 'stock1'), ('stock2', 'stock2')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(blank=True, null=True)),
                ('userbalance', models.IntegerField(default=1000000)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_of_stock', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
