# Generated by Django 3.1.1 on 2020-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock17',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock18',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock19',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock20',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock21',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock22',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock23',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock24',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock25',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock26',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock27',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock28',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock29',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock30',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock31',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock32',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock33',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.CharField(choices=[('ASHOKLEY', 'ASHOKLEY'), ('WIPRO', 'WIPRO'), ('RAJESHEXPO', 'RAJESHEXPO'), ('AMBUJACEM', 'AMBUJACEM'), ('MM', 'MM'), ('ONGC', 'ONGC'), ('DMART', 'DMART'), ('SUNPHARMA', 'SUNPHARMA'), ('stock9', 'stock9'), ('ADANIPOWER', 'ADANIPOWER'), ('stock11', 'stock11'), ('stock12', 'stock12'), ('stock13', 'stock13'), ('stock14', 'stock14'), ('stock15', 'stock15'), ('stock16', 'stock16'), ('stock17', 'stock17'), ('stock18', 'stock18'), ('stock19', 'stock19'), ('stock20', 'stock20'), ('stock21', 'stock21'), ('stock22', 'stock22'), ('stock23', 'stock23'), ('stock24', 'stock24'), ('stock25', 'stock25'), ('stock26', 'stock26'), ('stock27', 'stock27'), ('stock28', 'stock28'), ('stock29', 'stock29'), ('stock30', 'stock30'), ('stock31', 'stock31'), ('stock32', 'stock32'), ('stock33', 'stock33')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tradereq',
            name='stock',
            field=models.CharField(choices=[('ASHOKLEY', 'ASHOKLEY'), ('WIPRO', 'WIPRO'), ('RAJESHEXPO', 'RAJESHEXPO'), ('AMBUJACEM', 'AMBUJACEM'), ('MM', 'MM'), ('ONGC', 'ONGC'), ('DMART', 'DMART'), ('SUNPHARMA', 'SUNPHARMA'), ('stock9', 'stock9'), ('ADANIPOWER', 'ADANIPOWER'), ('stock11', 'stock11'), ('stock12', 'stock12'), ('stock13', 'stock13'), ('stock14', 'stock14'), ('stock15', 'stock15'), ('stock16', 'stock16'), ('stock17', 'stock17'), ('stock18', 'stock18'), ('stock19', 'stock19'), ('stock20', 'stock20'), ('stock21', 'stock21'), ('stock22', 'stock22'), ('stock23', 'stock23'), ('stock24', 'stock24'), ('stock25', 'stock25'), ('stock26', 'stock26'), ('stock27', 'stock27'), ('stock28', 'stock28'), ('stock29', 'stock29'), ('stock30', 'stock30'), ('stock31', 'stock31'), ('stock32', 'stock32'), ('stock33', 'stock33')], max_length=100),
        ),
    ]
