# Generated by Django 3.1.1 on 2020-11-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='userbalance',
            field=models.FloatField(default=100000.0),
        ),
    ]
