# Generated by Django 3.1.1 on 2020-11-02 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_stocklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='stockprice',
            field=models.FloatField(default=0),
        ),
    ]
