# Generated by Django 3.1.1 on 2020-10-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201007_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='userbalance',
            field=models.FloatField(default=1000000.0),
        ),
    ]
