# Generated by Django 3.1.1 on 2020-10-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_stock_userbalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='userbalance',
        ),
    ]
