# Generated by Django 3.1.1 on 2020-10-26 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20201026_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.CharField(choices=[('stock1', 'stock1'), ('stock2', 'stock2'), ('stock3', 'stock3'), ('stock4', 'stock4'), ('stock5', 'stock5'), ('stock6', 'stock6'), ('stock7', 'stock7'), ('stock8', 'stock8'), ('stock9', 'stock9'), ('stock10', 'stock10')], max_length=100)),
                ('numberofstocks', models.IntegerField(default=0)),
                ('priceperstock', models.FloatField(null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_trade', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_trade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
