# Generated by Django 3.1.1 on 2020-10-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tradereq'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradereq',
            name='action',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=10),
        ),
    ]
